# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PaperWinDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from images import ResourceImage
from screeninfo import get_monitors

class Ui_DialogPaperWin(object):
    def setupUi(self, DialogPaperWin):
        DialogPaperWin.setObjectName("DialogPaperWin")
        DialogPaperWin.resize(1016, 626)
        DialogPaperWin.setFixedSize(1000,626)
        for m in get_monitors():
          screenHeight = m.height
          screenWidth = m.width
        DialogPaperWin.setGeometry((screenWidth/2)-(1000/2),(screenHeight/2)-(768/2),1000,768)
        self.label_12 = QtWidgets.QLabel(DialogPaperWin)
        self.label_12.setGeometry(QtCore.QRect(390, 370, 201, 261))
        self.label_12.setStyleSheet("image: url(:/new/images/Hand_Big.png);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.pushButton_8 = QtWidgets.QPushButton(DialogPaperWin)
        self.pushButton_8.setGeometry(QtCore.QRect(360, 290, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_11 = QtWidgets.QLabel(DialogPaperWin)
        self.label_11.setGeometry(QtCore.QRect(400, -20, 201, 271))
        self.label_11.setStyleSheet("image: url(:/new/images/Rock_Big_Upside.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(DialogPaperWin)
        self.label_10.setGeometry(QtCore.QRect(400, 240, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.pushButton_7 = QtWidgets.QPushButton(DialogPaperWin)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 0, 31, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")

        self.retranslateUi(DialogPaperWin)
        QtCore.QMetaObject.connectSlotsByName(DialogPaperWin)

    def retranslateUi(self, DialogPaperWin):
        _translate = QtCore.QCoreApplication.translate
        DialogPaperWin.setWindowTitle(_translate("DialogPaperWin", "paper_win_dialog"))
        self.pushButton_8.setText(_translate("DialogPaperWin", "PLAY AGAIN"))
        self.label_10.setText(_translate("DialogPaperWin", "YOU WIN!"))
        self.pushButton_7.setText(_translate("DialogPaperWin", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogPaperWin = QtWidgets.QDialog()
    ui = Ui_DialogPaperWin()
    ui.setupUi(DialogPaperWin)
    DialogPaperWin.show()
    sys.exit(app.exec_())
